Fix Docker container names in pre-commit hooks
oxsecurity/megalinter pull request #1933
Opened 2022-10-05 03:53 UTC by mwarres

Fixes oxsecurity/megalinter#1932
The previous Docker container names contained Bash syntax, but pre-commit interprets them as string literals, resulting in invalid Docker container names. Remove Bash syntax, and replace it with string literals.

2022-10-05 08:31 UTC, nvuillam commented
@Kurt-von-Laven any opinion ? :)

2022-10-05 17:34 UTC, Kurt-von-Laven commented
It looks right to me. Just needs a rebase.

2022-10-05 19:59 UTC, nvuillam commented
@mwarres you know what to do :)

2022-10-06 19:10 UTC, Kurt-von-Laven requested changes

2022-10-06 19:10 UTC, Kurt-von-Laven commented on CHANGELOG.md
> +
Not sure whether this matters, but the addition of this blank line seems spurious. Everything else looks good.

2022-10-09 22:47 UTC, nvuillam approved these changes

2022-10-09 22:48 UTC, merged