docs: Fix REPOSITORY documentation
oxsecurity/megalinter pull request #2088
Opened 2022-11-18 15:32 UTC by ashokm

* Missing icon and text for REPOSITORY in ci_light.md
* Fix configuration keys for repository linters in repository.md

2022-11-18 17:50 UTC, Kurt-von-Laven requested changes

2022-11-18 17:50 UTC, Kurt-von-Laven commented on docs/descriptors/repository.md
> -| Linter                                 | Configuration key                           | Status
Thank you for the contribution, but see the comment at the top of the file. This file is auto-generated.

2022-11-20 00:34 UTC, nvuillam commented
name is automatically with descriptor + linter_name :)
To add icon, you need to add a file repository.icon in assets/icons :)

2022-11-20 10:30 UTC, nvuillam commented
> The docs/assets/icons/default.ico icon is already there.

I think it's looking for repository.ico ^^

> Also to fix the configuration keys in https://oxsecurity.github.io/megalinter/latest/descriptors/repository/:

Indeed very strange...

I'll checkout your branch (and maybe add some fix to complete your PR ^^ )

2022-11-25 11:33 UTC, closed without merging