Add PowerShell formatter linter
oxsecurity/megalinter pull request #2176
Opened 2022-12-23 00:21 UTC by bdovaz

@nvuillam I put it in draft because I have the doubt of how to create a test that fails if this command never fails... I pass it an input that is not even a valid powershell code and it works, that is, it does nothing and returns the same input as output....

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter?view=ps-modules

Formatter code that does not handle any errors:

https://github.com/PowerShell/PSScriptAnalyzer/blob/1.21.0/Engine/Formatter.cs

Unlike ScriptAnalyzer.cs which does handle errors (used by original powershell linter):

https://github.com/PowerShell/PSScriptAnalyzer/blob/1.21.0/Engine/ScriptAnalyzer.cs

2022-12-23 23:20 UTC, nvuillam commented
Don't forget to build with `bash build.sh`, it will generate the test class :)

2022-12-26 09:35 UTC, bdovaz commented
@nvuillam done.

Can you read and answer me to the first message of this PR related to the tests?

I see that there are special cases where you exclude this type of test (linter_failure):

https://github.com/oxsecurity/megalinter/blob/v6.16.0/megalinter/tests/test_megalinter/helpers/utilstest.py#L214

If we don't find a solution I don't know if this would be the solution.

2022-12-26 10:28 UTC, nvuillam commented
@bdovaz do powershell formatter have a --check mode, to just check if the file is already formatted or not ?

2022-12-26 11:22 UTC, bdovaz commented
@nvuillam as you can see, no:

https://learn.microsoft.com/en-us/powershell/module/psscriptanalyzer/invoke-formatter?view=ps-modules

2022-12-26 12:06 UTC, nvuillam commented
@bdovaz it seems that Microsoft does not like to build their apps like all others ^^

In that case you can add an empty file named `no_test_failure` (without extension) in the test folder

2022-12-26 12:14 UTC, nvuillam requested changes
plz check comment :)

2022-12-26 12:14 UTC, nvuillam commented on megalinter/descriptors/powershell.megalinter-descriptor.yml
> +    linter_url: https://github.com/PowerShell/PSScriptAnalyzer
@bdovaz plz add `    is_formatter: true` here :)

2022-12-26 12:21 UTC, bdovaz commented on megalinter/descriptors/powershell.megalinter-descriptor.yml
> +    linter_url: https://github.com/PowerShell/PSScriptAnalyzer
Done

2022-12-26 13:20 UTC, nvuillam commented
```shell
❌ Linted [REPOSITORY] files with [git_diff]: Found 1 error(s) - (0.03s)
- Using [git_diff v2.36.3] https://megalinter.io/2644adfa201ad6bd9bec5f21e8040cd699416064/descriptors/repository_git_diff
- MegaLinter key: [REPOSITORY_GIT_DIFF]
- Rules config: identified by [git_diff]
--Error detail:
.automation/test/powershell_formatter/good/powershell_good_1.ps1:2: new blank line at EOF.
.automation/test/powershell_formatter/good/powershell_good_1.psd1:4: new blank line at EOF.
.automation/test/powershell_formatter/good/powershell_good_1.psm1:2: new blank line at EOF.
```

That's really strange, I never saw this one :D 
Maybe some error while mananing conflicts ?

2022-12-26 14:14 UTC, bdovaz commented
> ```shell
> ❌ Linted [REPOSITORY] files with [git_diff]: Found 1 error(s) - (0.03s)
> - Using [git_diff v2.36.3] https://megalinter.io/2644adfa201ad6bd9bec5f21e8040cd699416064/descriptors/repository_git_diff
> - MegaLinter key: [REPOSITORY_GIT_DIFF]
> - Rules config: identified by [git_diff]
> --Error detail:
> .automation/test/powershell_formatter/good/powershell_good_1.ps1:2: new blank line at EOF.
> .automation/test/powershell_formatter/good/powershell_good_1.psd1:4: new blank line at EOF.
> .automation/test/powershell_formatter/good/powershell_good_1.psm1:2: new blank line at EOF.
> ```
> 
> That's really strange, I never saw this one :D Maybe some error while mananing conflicts ?

Well I don't know what to do to fix this because if you look at my PR I simply copied the 3 files from the powershell folder as is.

2022-12-26 15:40 UTC, nvuillam commented
@bdovaz what if you add a blank line in the files so they errors can disappear ?

2022-12-26 17:27 UTC, bdovaz commented
@nvuillam I just did it but that is the solution? I just don't understand the error either, what it refers to and how to fix it.

Let's wait for the result of the build.

2022-12-26 18:53 UTC, nvuillam commented
That's really really strange... as the rest seems legit,  I force the PR, we'll see if it solves the issue ^^

2022-12-26 18:53 UTC, merged

2022-12-26 18:58 UTC, echoix commented
This reminds me of when git changes the end of lines when checking-out, and changing them back when committing. It is normally controlled by a .gitattributes file (like https://github.com/oxsecurity/megalinter/blob/main/.gitattributes ). Are you working on Windows?

2022-12-26 19:17 UTC, bdovaz commented
> This reminds me of when git changes the end of lines when checking-out, and changing them back when committing. It is normally controlled by a .gitattributes file (like https://github.com/oxsecurity/megalinter/blob/main/.gitattributes ). Are you working on Windows?

@nvuillam @echoix yes, I'm on Windows.

2022-12-26 19:46 UTC, nvuillam commented
I'm on windows too but never had the issue ^^

If it does not happen on this PR https://github.com/oxsecurity/megalinter/pull/2189 , let's consider the problem solved ^^

2022-12-26 22:59 UTC, nvuillam commented
I learned something today :)

https://stackoverflow.com/questions/27059239/git-new-blank-line-at-eof

2022-12-27 00:30 UTC, echoix commented
> I'm on windows too but never had the issue ^^

Some of the .gitattributes won't get applied to an already cloned repo without any actions, so it doesn't exclude the problem. 

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

https://git-scm.com/docs/gitattributes

2022-12-27 16:30 UTC, nvuillam commented
Finally solved... i just remove the line at the end of the files >_<