fix(pre-commit): corrected pre-commit args for megalinter-full
oxsecurity/megalinter pull request #2411
Opened 2023-03-03 21:21 UTC by drbothen

containernam argument contained bot the flag and value on the same line. These have to be separate line

Fixes #

## Proposed Changes

1. ...
2. ...
3. ...

## Readiness Checklist

### Author/Contributor
- [ ] Add entry to the [CHANGELOG](https://github.com/oxsecurity/megalinter/blob/main/CHANGELOG.md) listing the change and linking to the corresponding issue (if appropriate)
- [ ] If documentation is needed for this change, has that been included in this pull request

### Reviewing Maintainer
- [ ] Label as `breaking` if this is a large fundamental change
- [ ] Label as either `automation`, `bug`, `documentation`, `enhancement`, `infrastructure`, or `performance`

2023-03-03 23:14 UTC, Kurt-von-Laven commented
Can you elaborate on how to reproduce this error? We have been using the pre-commit hooks successfully for a while now. You are the second person to report this, but I would like to know how I can meaningfully test this change.

2023-03-04 03:38 UTC, drbothen commented
> Can you elaborate on how to reproduce this error? We have been using the pre-commit hooks successfully for a while now. You are the second person to report this, but I would like to know how I can meaningfully test this change.

For sure, I installed it using ` npm install mega-linter-runner -g`  on my ubuntu server (Ubuntu 22.04.1 LTS) development environment. My dev environment has dual 64-core AMD EPYC with 1TB of RAM. 

my pre-commit is configured using the following:

`exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main, --branch, develop]
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/oxsecurity/megalinter
    rev: v6.19.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - commit
      - id: megalinter-full # Slower, more thorough
        stages:
          - push

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
`

The above config will generate the below error when magalinter-full is triggered

`[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /home/jmagady.fam@ad.recitsols.com/.cache/pre-commit/patch1677900863-182882.
pyupgrade............................................(no files to check)Skipped
check for added large files..............................................Passed
check for case conflicts.................................................Passed
check for merge conflicts................................................Passed
check for broken symlinks............................(no files to check)Skipped
detect destroyed symlinks................................................Passed
detect private key.......................................................Passed
check json...........................................(no files to check)Skipped
check yaml...............................................................Passed
don't commit to branch...................................................Passed
fix end of files.........................................................Passed
forbid new submodules................................(no files to check)Skipped
trim trailing whitespace.................................................Passed
Run MegaLinter...........................................................Failed
- hook id: megalinter-full
- exit code: 1

/usr/lib/node_modules/mega-linter-runner/node_modules/optionator/lib/index.js:316
          throw new Error("Value for '" + prop + "' of type '" + getOption(prop).type + "' required.");
                ^

Error: Value for 'container-name' of type 'String' required.
    at checkProp (/usr/lib/node_modules/mega-linter-runner/node_modules/optionator/lib/index.js:316:17)
    at Object.parse (/usr/lib/node_modules/mega-linter-runner/node_modules/optionator/lib/index.js:356:13)
    at MegaLinterRunnerCli.run (/usr/lib/node_modules/mega-linter-runner/lib/cli.js:10:39)
    at /usr/lib/node_modules/mega-linter-runner/lib/index.js:13:37
    at Object.<anonymous> (/usr/lib/node_modules/mega-linter-runner/lib/index.js:14:5)
    at Module._compile (node:internal/modules/cjs/loader:1226:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1280:10)
    at Module.load (node:internal/modules/cjs/loader:1089:32)
    at Module._load (node:internal/modules/cjs/loader:930:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)

Node.js v18.14.0
`
if I change the pre-commit config to the following, the error goes away:

`exclude: "^docs/|/migrations/"
default_stages: [commit]

repos:
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.0
    hooks:
      - id: commitizen

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: check-json
      - id: check-yaml
      - id: no-commit-to-branch
        args: [--branch, main, --branch, develop]
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: trailing-whitespace

  - repo: https://github.com/oxsecurity/megalinter
    rev: v6.19.0 # Git tag specifying the hook, not mega-linter-runner, version
    hooks:
      - id: megalinter-incremental # Faster, less thorough
        stages:
          - commit
      - id: megalinter-full # Slower, more thorough
        # below required until PR #2411 is merged https://github.com/oxsecurity/megalinter/pull/2411
        args:
          - mega-linter-runner
          - --containername
          - "megalinter-full"
          - --remove-container
          - --fix
          - --env
          - "'APPLY_FIXES=all'"
          - --env
          - "'CLEAR_REPORT_FOLDER=true'"
          - --env
          - "'LOG_LEVEL=warning'"
        stages:
          - push

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
`
In the code on megaliter-incremental, you define the arg flags and values on separate lines. I replicated this behavior for magalinter-full and it resolved the error.

Does this help?

2023-03-04 22:00 UTC, Kurt-von-Laven requested changes
Thank you for catching this. I was able to reproduce this issue following the steps you provided!

2023-03-04 23:00 UTC, nvuillam approved these changes
Thanks for catching the issue and fixing it :)

2023-03-04 23:00 UTC, merged