Re-enabled: tsqllint
oxsecurity/megalinter pull request #4120
Opened 2024-10-13 10:57 UTC by TommyE123

[tsqllint](https://github.com/tsqllint/tsqllint) Re-enabled after .net 8 and security updates.

2024-10-30 03:49 UTC, nvuillam commented
@TommyE123 plz can you check the failing tsqllint test case ? :)

2024-11-01 22:16 UTC, echoix requested changes

2024-11-01 22:16 UTC, echoix commented on CHANGELOG.md
> +  - [tsqllint](https://github.com/tsqllint/tsqllint) Re-enabled after .net 8 and security updates
This section is in an already released version. Can you place it in the unreleased section above?

2024-11-01 22:34 UTC, echoix approved these changes

2024-11-04 17:51 UTC, echoix commented
There seems to be some conflicts now

2024-11-05 17:21 UTC, merged